### ISSUE TITLE
error in merging multiple endpoints for filter for HeFQUIN

### ISSUE THREAD

**Issue by micheldumontier** [MaastrichtU-IDS/federatedQueryKG#6]
```
micheldumontier@FSELAP0508:~/code/external/HeFQUIN$ java -cp target/HeFQUIN-0.0.1-SNAPSHOT.jar se.liu.ida.hefquin.cli.RunQueryWithoutSrcSel --federationDescription=ExampleFederation.ttl --query=bio2rdf-drug-model-phenotypes.rq
class org.apache.jena.sparql.syntax.ElementGroup cannot be cast to class org.apache.jena.sparql.syntax.ElementPathBlock (org.apache.jena.sparql.syntax.ElementGroup and org.apache.jena.sparql.syntax.ElementPathBlock are in unnamed module of loader 'app')
java.lang.ClassCastException: class org.apache.jena.sparql.syntax.ElementGroup cannot be cast to class org.apache.jena.sparql.syntax.ElementPathBlock (org.apache.jena.sparql.syntax.ElementGroup and org.apache.jena.sparql.syntax.ElementPathBlock are in unnamed module of loader 'app')
        at se.liu.ida.hefquin.engine.query.impl.QueryPatternUtils.merge(QueryPatternUtils.java:1111)
        at se.liu.ida.hefquin.engine.query.impl.QueryPatternUtils.merge(QueryPatternUtils.java:862)
        at se.liu.ida.hefquin.engine.federation.access.utils.SPARQLRequestUtils.merge(SPARQLRequestUtils.java:20)
        at se.liu.ida.hefquin.engine.queryproc.impl.loptimizer.heuristics.MergeRequests.mergeGraphPatternIntoSPARQLRequest(MergeRequests.java:388)
        at se.liu.ida.hefquin.engine.queryproc.impl.loptimizer.heuristics.MergeRequests.mergeSPARQLRequestsViaJoin(MergeRequests.java:416)
        at se.liu.ida.hefquin.engine.queryproc.impl.loptimizer.heuristics.MergeRequests.mergeSPARQLRequestsViaJoin(MergeRequests.java:437)
        at se.liu.ida.hefquin.engine.queryproc.impl.loptimizer.heuristics.MergeRequests.apply(MergeRequests.java:310)
        at se.liu.ida.hefquin.engine.queryproc.impl.loptimizer.LogicalOptimizerImpl.optimize(LogicalOptimizerImpl.java:47)
        at se.liu.ida.hefquin.engine.queryproc.impl.planning.QueryPlannerImpl.createPlan(QueryPlannerImpl.java:69)
        at se.liu.ida.hefquin.engine.queryproc.impl.QueryProcessorImpl.processQuery(QueryProcessorImpl.java:61)
        at se.liu.ida.hefquin.jenaintegration.sparql.engine.main.OpExecutorHeFQUIN$MainQueryIterator.nextStage(OpExecutorHeFQUIN.java:227)
        at org.apache.jena.sparql.engine.iterator.QueryIterRepeatApply.makeNextStage(QueryIterRepeatApply.java:100)
        at org.apache.jena.sparql.engine.iterator.QueryIterRepeatApply.hasNextBinding(QueryIterRepeatApply.java:60)
        at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
        at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:38)
        at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
        at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:38)
        at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
        at org.apache.jena.sparql.engine.ResultSetStream.hasNext(ResultSetStream.java:64)
        at org.apache.jena.sparql.engine.ResultSetCheckCondition.hasNext(ResultSetCheckCondition.java:55)
        at org.apache.jena.sparql.resultset.ResultSetMem.<init>(ResultSetMem.java:89)
        at org.apache.jena.query.ResultSetFactory.makeRewindable(ResultSetFactory.java:311)
        at org.apache.jena.query.ResultSet.rewindable(ResultSet.java:83)
        at org.apache.jena.riot.resultset.rw.ResultSetWriterText.output$(ResultSetWriterText.java:132)
        at org.apache.jena.riot.resultset.rw.ResultSetWriterText.output(ResultSetWriterText.java:120)
        at org.apache.jena.riot.resultset.rw.ResultSetWriterText.output(ResultSetWriterText.java:116)
        at org.apache.jena.riot.resultset.rw.ResultSetWriterText.write(ResultSetWriterText.java:59)
        at org.apache.jena.riot.resultset.rw.ResultsWriter.write(ResultsWriter.java:156)
        at org.apache.jena.riot.resultset.rw.ResultsWriter.write(ResultsWriter.java:126)
        at org.apache.jena.sparql.util.QueryExecUtils.outputResultSet(QueryExecUtils.java:133)
        at org.apache.jena.sparql.util.QueryExecUtils.doSelectQuery(QueryExecUtils.java:150)
        at org.apache.jena.sparql.util.QueryExecUtils.executeQuery(QueryExecUtils.java:81)
        at se.liu.ida.hefquin.engine.HeFQUINEngineBuilder$MyEngine.executeQuery(HeFQUINEngineBuilder.java:169)
        at se.liu.ida.hefquin.cli.RunQueryWithoutSrcSel.exec(RunQueryWithoutSrcSel.java:105)
        at org.apache.jena.cmd.CmdMain.mainMethod(CmdMain.java:92)
        at org.apache.jena.cmd.CmdMain.mainRun(CmdMain.java:58)
        at org.apache.jena.cmd.CmdMain.mainRun(CmdMain.java:45)
        at se.liu.ida.hefquin.cli.RunQueryWithoutSrcSel.main(RunQueryWithoutSrcSel.java:49)
```

``` PREFIX mp: <http://purl.obolibrary.org/obo/MP_>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
SELECT * # distinct ?phenotype_label

{
    SERVICE <http://bio2rdf.org/sparql> {
     #?drug <http://bio2rdf.org/drugbank_vocabulary:target> ?target .
     <http://bio2rdf.org/drugbank:DB00619> <http://bio2rdf.org/drugbank_vocabulary:target> ?target .
     #FILTER(?drug = )
     ?target <http://bio2rdf.org/drugbank_vocabulary:x-hgnc> ?hgnc .
   }
  SERVICE <http://bio2rdf.org/sparql> {
    ?hgnc <http://bio2rdf.org/hgnc_vocabulary:x-mgi> ?marker .
   }    
  SERVICE <http://bio2rdf.org/sparql> {
    ?model <http://bio2rdf.org/mgi_vocabulary:marker> ?marker .
    ?model <http://bio2rdf.org/mgi_vocabulary:allele> ?all .
    ?all <http://bio2rdf.org/mgi_vocabulary:allele-attribute> ?allele_type .
    ?model <http://bio2rdf.org/mgi_vocabulary:phenotype> ?phenotypes .
    FILTER (str(?allele_type) = "Null/knockout") 
   }
```

```
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX fd:     <http://www.example.org/se/liu/ida/hefquin/fd#>
PREFIX ex:     <http://example.org/>

ex:bio2rdfSPARQL
      a            fd:FederationMember ;
      fd:interface [ a                  fd:SPARQLEndpointInterface ;
                     fd:endpointAddress <http://bio2rdf.org/sparql> ] .
```

**Comment by micheldumontier** [comment]
commenting out mergeRequests allows the query to go forward

```public LogicalOptimizerImpl() {
		final HeuristicForLogicalOptimization mergeRequests = new MergeRequests();

		//// It has turned out that UnionPullUp typically does more
		//// harm than good. For more details, see the end of the
		//// JavaDoc comment for UnionPullUp.
		//heuristics.add( new UnionPullUp() );

	//heuristics.add( mergeRequests );
		heuristics.add( new FilterPushDown() );
		//heuristics.add( mergeRequests );
```

**Comment by hartig** [comment]
Fixed by https://github.com/LiUSemWeb/HeFQUIN/pull/290
